## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN','NAME','ASK_AMT'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,1

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE          17
AFFILIATION                6
CLASSIFICATION            71
USE_CASE                   5
ORGANIZATION               4
STATUS                     2
INCOME_AMT                 9
SPECIAL_CONSIDERATIONS     2
IS_SUCCESSFUL              2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
type = application_df['APPLICATION_TYPE'].value_counts()
type

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(type.iloc[12:].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
classification_count[classification_count>1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_count.iloc[12:].index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      574
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
application_numeric = pd.get_dummies(application_df, dtype= int)
application_numeric.head()

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,1,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,1,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,1,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
4,1,1,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,1,0

In [11]:
y = application_numeric['IS_SUCCESSFUL'].values

In [12]:
X= application_numeric.drop(columns = 'IS_SUCCESSFUL').values
X

array([[1, 0, 1, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0]])

In [13]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [15]:
X_train.shape

(25724, 53)

In [16]:
y_train.shape

(25724,)

## Compile, Train and Evaluate the Model

In [17]:
#Method 2- Drop the "Ask imc" column, change activation to sigmoid, and one more layer, increase epoch
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(input_dim=53, units=15, activation="sigmoid"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=8, activation="sigmoid"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=4, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 15)                810

 dense_1 (Dense)             (None, 8)                 128

 dense_2 (Dense)             (None, 4)                 36

 dense_3 (Dense)             (None, 1)                 5

=================================================================
Total params: 979 (3.82 KB)
Trainable params: 979 (3.82 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=160)

Epoch 1/160
804/804 [==============================] - 0s 376us/step - loss: 0.6521 - accuracy: 0.6361
Epoch 2/160
804/804 [==============================] - 0s 369us/step - loss: 0.5767 - accuracy: 0.7287
Epoch 3/160
804/804 [==============================] - 0s 366us/step - loss: 0.5724 - accuracy: 0.7302
Epoch 4/160
804/804 [==============================] - 0s 368us/step - loss: 0.5714 - accuracy: 0.7302
Epoch 5/160
804/804 [==============================] - 0s 365us/step - loss: 0.5710 - accuracy: 0.7304
Epoch 6/160
804/804 [==============================] - 0s 369us/step - loss: 0.5705 - accuracy: 0.7301
Epoch 7/160
804/804 [==============================] - 0s 369us/step - loss: 0.5701 - accuracy: 0.7313
Epoch 8/160
804/804 [==============================] - 0s 376us/step - loss: 0.5694 - accuracy: 0.7318
Epoch 9/160
804/804 [==============================] - 0s 396us/step - loss: 0.5689 - accuracy: 0.7315
Epoch 10/160
804/804 [==============================] - 0s 383us/step - loss: 0.5674 - accuracy: 0.7319
Epoch 11/160
804/804 [==============================] - 0s 399us/step - loss: 0.5651 - accuracy: 0.7323
Epoch 12/160
804/804 [==============================] - 0s 419us/step - loss: 0.5617 - accuracy: 0.7315
Epoch 13/160
804/804 [==============================] - 0s 397us/step - loss: 0.5590 - accuracy: 0.7329
Epoch 14/160
804/804 [==============================] - 0s 408us/step - loss: 0.5568 - accuracy: 0.7317
Epoch 15/160
804/804 [==============================] - 0s 382us/step - loss: 0.5550 - accuracy: 0.7325
Epoch 16/160
804/804 [==============================] - 0s 431us/step - loss: 0.5536 - accuracy: 0.7321
Epoch 17/160
804/804 [==============================] - 0s 501us/step - loss: 0.5527 - accuracy: 0.7313
Epoch 18/160
804/804 [==============================] - 0s 395us/step - loss: 0.5518 - accuracy: 0.7320
Epoch 19/160
804/804 [==============================] - 0s 418us/step - loss: 0.5513 - accuracy: 0.7322
Epoch 20/160
804/804 [==============================] - 0s 595us/step - loss: 0.5506 - accuracy: 0.7334
Epoch 21/160
804/804 [==============================] - 0s 542us/step - loss: 0.5498 - accuracy: 0.7317
Epoch 22/160
804/804 [==============================] - 0s 490us/step - loss: 0.5494 - accuracy: 0.7320
Epoch 23/160
804/804 [==============================] - 0s 502us/step - loss: 0.5489 - accuracy: 0.7325
Epoch 24/160
804/804 [==============================] - 0s 470us/step - loss: 0.5481 - accuracy: 0.7331
Epoch 25/160
804/804 [==============================] - 0s 426us/step - loss: 0.5480 - accuracy: 0.7325
Epoch 26/160
804/804 [==============================] - 0s 411us/step - loss: 0.5474 - accuracy: 0.7338
Epoch 27/160
804/804 [==============================] - 0s 396us/step - loss: 0.5470 - accuracy: 0.7335
Epoch 28/160
804/804 [==============================] - 0s 397us/step - loss: 0.5467 - accuracy: 0.7348
Epoch 29/160
804/804 [==============================] - 0s 394us/step - loss: 0.5465 - accuracy: 0.7329
Epoch 30/160
804/804 [==============================] - 0s 390us/step - loss: 0.5463 - accuracy: 0.7336
Epoch 31/160
804/804 [==============================] - 0s 398us/step - loss: 0.5457 - accuracy: 0.7328
Epoch 32/160
804/804 [==============================] - 0s 450us/step - loss: 0.5457 - accuracy: 0.7339
Epoch 33/160
804/804 [==============================] - 0s 463us/step - loss: 0.5455 - accuracy: 0.7341
Epoch 34/160
804/804 [==============================] - 0s 417us/step - loss: 0.5449 - accuracy: 0.7338
Epoch 35/160
804/804 [==============================] - 0s 403us/step - loss: 0.5448 - accuracy: 0.7340
Epoch 36/160
804/804 [==============================] - 0s 395us/step - loss: 0.5444 - accuracy: 0.7341
Epoch 37/160
804/804 [==============================] - 0s 395us/step - loss: 0.5443 - accuracy: 0.7345
Epoch 38/160
804/804 [==============================] - 0s 431us/step - loss: 0.5441 - accuracy: 0.7347
Epoch 39/160
804/804 [==============================] - 0s 404us/step - loss: 0.5439 - accuracy: 0.7337
Epoch 40/160
804/804 [==============================] - 0s 397us/step - loss: 0.5437 - accuracy: 0.7348
Epoch 41/160
804/804 [==============================] - 0s 389us/step - loss: 0.5436 - accuracy: 0.7348
Epoch 42/160
804/804 [==============================] - 0s 378us/step - loss: 0.5432 - accuracy: 0.7350
Epoch 43/160
804/804 [==============================] - 0s 373us/step - loss: 0.5430 - accuracy: 0.7355
Epoch 44/160
804/804 [==============================] - 0s 376us/step - loss: 0.5431 - accuracy: 0.7357
Epoch 45/160
804/804 [==============================] - 0s 374us/step - loss: 0.5428 - accuracy: 0.7355
Epoch 46/160
804/804 [==============================] - 0s 374us/step - loss: 0.5425 - accuracy: 0.7357
Epoch 47/160
804/804 [==============================] - 0s 381us/step - loss: 0.5422 - accuracy: 0.7358
Epoch 48/160
804/804 [==============================] - 0s 381us/step - loss: 0.5421 - accuracy: 0.7363
Epoch 49/160
804/804 [==============================] - 0s 375us/step - loss: 0.5422 - accuracy: 0.7359
Epoch 50/160
804/804 [==============================] - 0s 373us/step - loss: 0.5421 - accuracy: 0.7361
Epoch 51/160
804/804 [==============================] - 0s 385us/step - loss: 0.5418 - accuracy: 0.7365
Epoch 52/160
804/804 [==============================] - 0s 383us/step - loss: 0.5417 - accuracy: 0.7358
Epoch 53/160
804/804 [==============================] - 0s 374us/step - loss: 0.5415 - accuracy: 0.7357
Epoch 54/160
804/804 [==============================] - 0s 371us/step - loss: 0.5413 - accuracy: 0.7364
Epoch 55/160
804/804 [==============================] - 0s 378us/step - loss: 0.5411 - accuracy: 0.7366
Epoch 56/160
804/804 [==============================] - 0s 420us/step - loss: 0.5411 - accuracy: 0.7368
Epoch 57/160
804/804 [==============================] - 0s 374us/step - loss: 0.5411 - accuracy: 0.7357
Epoch 58/160
804/804 [==============================] - 0s 375us/step - loss: 0.5408 - accuracy: 0.7370
Epoch 59/160
804/804 [==============================] - 0s 374us/step - loss: 0.5406 - accuracy: 0.7366
Epoch 60/160
804/804 [==============================] - 0s 372us/step - loss: 0.5406 - accuracy: 0.7365
Epoch 61/160
804/804 [==============================] - 0s 371us/step - loss: 0.5404 - accuracy: 0.7357
Epoch 62/160
804/804 [==============================] - 0s 372us/step - loss: 0.5403 - accuracy: 0.7357
Epoch 63/160
804/804 [==============================] - 0s 373us/step - loss: 0.5399 - accuracy: 0.7374
Epoch 64/160
804/804 [==============================] - 0s 378us/step - loss: 0.5399 - accuracy: 0.7369
Epoch 65/160
804/804 [==============================] - 0s 377us/step - loss: 0.5398 - accuracy: 0.7362
Epoch 66/160
804/804 [==============================] - 0s 420us/step - loss: 0.5396 - accuracy: 0.7371
Epoch 67/160
804/804 [==============================] - 0s 375us/step - loss: 0.5394 - accuracy: 0.7369
Epoch 68/160
804/804 [==============================] - 0s 373us/step - loss: 0.5395 - accuracy: 0.7369
Epoch 69/160
804/804 [==============================] - 0s 374us/step - loss: 0.5394 - accuracy: 0.7376
Epoch 70/160
804/804 [==============================] - 0s 374us/step - loss: 0.5393 - accuracy: 0.7370
Epoch 71/160
804/804 [==============================] - 0s 375us/step - loss: 0.5390 - accuracy: 0.7376
Epoch 72/160
804/804 [==============================] - 0s 416us/step - loss: 0.5391 - accuracy: 0.7374
Epoch 73/160
804/804 [==============================] - 0s 378us/step - loss: 0.5390 - accuracy: 0.7384
Epoch 74/160
804/804 [==============================] - 0s 377us/step - loss: 0.5389 - accuracy: 0.7380
Epoch 75/160
804/804 [==============================] - 0s 375us/step - loss: 0.5386 - accuracy: 0.7375
Epoch 76/160
804/804 [==============================] - 0s 374us/step - loss: 0.5384 - accuracy: 0.7374
Epoch 77/160
804/804 [==============================] - 0s 371us/step - loss: 0.5386 - accuracy: 0.7378
Epoch 78/160
804/804 [==============================] - 0s 374us/step - loss: 0.5381 - accuracy: 0.7381
Epoch 79/160
804/804 [==============================] - 0s 371us/step - loss: 0.5384 - accuracy: 0.7368
Epoch 80/160
804/804 [==============================] - 0s 374us/step - loss: 0.5382 - accuracy: 0.7386
Epoch 81/160
804/804 [==============================] - 0s 376us/step - loss: 0.5382 - accuracy: 0.7368
Epoch 82/160
804/804 [==============================] - 0s 385us/step - loss: 0.5383 - accuracy: 0.7372
Epoch 83/160
804/804 [==============================] - 0s 381us/step - loss: 0.5381 - accuracy: 0.7375
Epoch 84/160
804/804 [==============================] - 0s 417us/step - loss: 0.5380 - accuracy: 0.7378
Epoch 85/160
804/804 [==============================] - 0s 423us/step - loss: 0.5378 - accuracy: 0.7376
Epoch 86/160
804/804 [==============================] - 0s 376us/step - loss: 0.5378 - accuracy: 0.7372
Epoch 87/160
804/804 [==============================] - 0s 378us/step - loss: 0.5380 - accuracy: 0.7377
Epoch 88/160
804/804 [==============================] - 0s 372us/step - loss: 0.5376 - accuracy: 0.7374
Epoch 89/160
804/804 [==============================] - 0s 372us/step - loss: 0.5376 - accuracy: 0.7381
Epoch 90/160
804/804 [==============================] - 0s 374us/step - loss: 0.5375 - accuracy: 0.7378
Epoch 91/160
804/804 [==============================] - 0s 373us/step - loss: 0.5375 - accuracy: 0.7382
Epoch 92/160
804/804 [==============================] - 0s 372us/step - loss: 0.5376 - accuracy: 0.7389
Epoch 93/160
804/804 [==============================] - 0s 375us/step - loss: 0.5373 - accuracy: 0.7382
Epoch 94/160
804/804 [==============================] - 0s 375us/step - loss: 0.5374 - accuracy: 0.7378
Epoch 95/160
804/804 [==============================] - 0s 415us/step - loss: 0.5373 - accuracy: 0.7386
Epoch 96/160
804/804 [==============================] - 0s 382us/step - loss: 0.5371 - accuracy: 0.7386
Epoch 97/160
804/804 [==============================] - 0s 374us/step - loss: 0.5370 - accuracy: 0.7383
Epoch 98/160
804/804 [==============================] - 0s 374us/step - loss: 0.5372 - accuracy: 0.7378
Epoch 99/160
804/804 [==============================] - 0s 376us/step - loss: 0.5369 - accuracy: 0.7385
Epoch 100/160
804/804 [==============================] - 0s 375us/step - loss: 0.5371 - accuracy: 0.7381
Epoch 101/160
804/804 [==============================] - 0s 379us/step - loss: 0.5367 - accuracy: 0.7380
Epoch 102/160
804/804 [==============================] - 0s 377us/step - loss: 0.5369 - accuracy: 0.7382
Epoch 103/160
804/804 [==============================] - 0s 417us/step - loss: 0.5367 - accuracy: 0.7378
Epoch 104/160
804/804 [==============================] - 0s 376us/step - loss: 0.5369 - accuracy: 0.7383
Epoch 105/160
804/804 [==============================] - 0s 375us/step - loss: 0.5370 - accuracy: 0.7388
Epoch 106/160
804/804 [==============================] - 0s 425us/step - loss: 0.5367 - accuracy: 0.7384
Epoch 107/160
804/804 [==============================] - 0s 382us/step - loss: 0.5369 - accuracy: 0.7380
Epoch 108/160
804/804 [==============================] - 0s 382us/step - loss: 0.5365 - accuracy: 0.7392
Epoch 109/160
804/804 [==============================] - 0s 373us/step - loss: 0.5364 - accuracy: 0.7383
Epoch 110/160
804/804 [==============================] - 0s 373us/step - loss: 0.5364 - accuracy: 0.7384
Epoch 111/160
804/804 [==============================] - 0s 376us/step - loss: 0.5364 - accuracy: 0.7381
Epoch 112/160
804/804 [==============================] - 0s 378us/step - loss: 0.5363 - accuracy: 0.7387
Epoch 113/160
804/804 [==============================] - 0s 376us/step - loss: 0.5361 - accuracy: 0.7368
Epoch 114/160
804/804 [==============================] - 0s 372us/step - loss: 0.5362 - accuracy: 0.7388
Epoch 115/160
804/804 [==============================] - 0s 418us/step - loss: 0.5364 - accuracy: 0.7389
Epoch 116/160
804/804 [==============================] - 0s 428us/step - loss: 0.5362 - accuracy: 0.7377
Epoch 117/160
804/804 [==============================] - 0s 384us/step - loss: 0.5361 - accuracy: 0.7389
Epoch 118/160
804/804 [==============================] - 0s 385us/step - loss: 0.5362 - accuracy: 0.7382
Epoch 119/160
804/804 [==============================] - 0s 380us/step - loss: 0.5361 - accuracy: 0.7381
Epoch 120/160
804/804 [==============================] - 0s 380us/step - loss: 0.5362 - accuracy: 0.7379
Epoch 121/160
804/804 [==============================] - 0s 374us/step - loss: 0.5360 - accuracy: 0.7385
Epoch 122/160
804/804 [==============================] - 0s 378us/step - loss: 0.5362 - accuracy: 0.7390
Epoch 123/160
804/804 [==============================] - 0s 423us/step - loss: 0.5357 - accuracy: 0.7383
Epoch 124/160
804/804 [==============================] - 0s 391us/step - loss: 0.5359 - accuracy: 0.7374
Epoch 125/160
804/804 [==============================] - 0s 378us/step - loss: 0.5359 - accuracy: 0.7380
Epoch 126/160
804/804 [==============================] - 0s 378us/step - loss: 0.5358 - accuracy: 0.7382
Epoch 127/160
804/804 [==============================] - 0s 375us/step - loss: 0.5357 - accuracy: 0.7386
Epoch 128/160
804/804 [==============================] - 0s 375us/step - loss: 0.5356 - accuracy: 0.7386
Epoch 129/160
804/804 [==============================] - 0s 380us/step - loss: 0.5359 - accuracy: 0.7377
Epoch 130/160
804/804 [==============================] - 0s 384us/step - loss: 0.5355 - accuracy: 0.7382
Epoch 131/160
804/804 [==============================] - 0s 376us/step - loss: 0.5356 - accuracy: 0.7383
Epoch 132/160
804/804 [==============================] - 0s 426us/step - loss: 0.5356 - accuracy: 0.7392
Epoch 133/160
804/804 [==============================] - 0s 380us/step - loss: 0.5354 - accuracy: 0.7385
Epoch 134/160
804/804 [==============================] - 0s 380us/step - loss: 0.5354 - accuracy: 0.7386
Epoch 135/160
804/804 [==============================] - 0s 379us/step - loss: 0.5355 - accuracy: 0.7379
Epoch 136/160
804/804 [==============================] - 0s 381us/step - loss: 0.5354 - accuracy: 0.7382
Epoch 137/160
804/804 [==============================] - 0s 383us/step - loss: 0.5353 - accuracy: 0.7390
Epoch 138/160
804/804 [==============================] - 0s 378us/step - loss: 0.5353 - accuracy: 0.7397
Epoch 139/160
804/804 [==============================] - 0s 420us/step - loss: 0.5350 - accuracy: 0.7381
Epoch 140/160
804/804 [==============================] - 0s 422us/step - loss: 0.5353 - accuracy: 0.7389
Epoch 141/160
804/804 [==============================] - 0s 375us/step - loss: 0.5352 - accuracy: 0.7385
Epoch 142/160
804/804 [==============================] - 0s 376us/step - loss: 0.5352 - accuracy: 0.7388
Epoch 143/160
804/804 [==============================] - 0s 375us/step - loss: 0.5351 - accuracy: 0.7383
Epoch 144/160
804/804 [==============================] - 0s 385us/step - loss: 0.5352 - accuracy: 0.7390
Epoch 145/160
804/804 [==============================] - 0s 377us/step - loss: 0.5350 - accuracy: 0.7389
Epoch 146/160
804/804 [==============================] - 0s 481us/step - loss: 0.5350 - accuracy: 0.7391
Epoch 147/160
804/804 [==============================] - 0s 381us/step - loss: 0.5350 - accuracy: 0.7387
Epoch 148/160
804/804 [==============================] - 0s 376us/step - loss: 0.5350 - accuracy: 0.7389
Epoch 149/160
804/804 [==============================] - 0s 381us/step - loss: 0.5350 - accuracy: 0.7392
Epoch 150/160
804/804 [==============================] - 0s 390us/step - loss: 0.5350 - accuracy: 0.7396
Epoch 151/160
804/804 [==============================] - 0s 374us/step - loss: 0.5348 - accuracy: 0.7399
Epoch 152/160
804/804 [==============================] - 0s 380us/step - loss: 0.5344 - accuracy: 0.7388
Epoch 153/160
804/804 [==============================] - 0s 421us/step - loss: 0.5347 - accuracy: 0.7396
Epoch 154/160
804/804 [==============================] - 0s 377us/step - loss: 0.5347 - accuracy: 0.7381
Epoch 155/160
804/804 [==============================] - 0s 376us/step - loss: 0.5349 - accuracy: 0.7388
Epoch 156/160
804/804 [==============================] - 0s 376us/step - loss: 0.5347 - accuracy: 0.7381
Epoch 157/160
804/804 [==============================] - 0s 373us/step - loss: 0.5347 - accuracy: 0.7386
Epoch 158/160
804/804 [==============================] - 0s 376us/step - loss: 0.5344 - accuracy: 0.7393
Epoch 159/160
804/804 [==============================] - 0s 374us/step - loss: 0.5346 - accuracy: 0.7387
Epoch 160/160
804/804 [==============================] - 0s 420us/step - loss: 0.5346 - accuracy: 0.7385

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5499 - accuracy: 0.7313 - 136ms/epoch - 507us/step
Loss: 0.5498935580253601, Accuracy: 0.7313119769096375

In [21]:
# Export our model to HDF5 file
nn.save("alphabetsoupcharity_optumization_2.h5")

/Users/candice/anaconda3/envs/ml/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(